package bookscrabble.client;

public class Error_Codes {
    public static final String OK = "#OK", UNKNOWN_CMD = "#UNKNOWN_CMD", INVALID_ARGS = "#INVALID_ARGS", 
    MISSING_ARGS = "#MISSING_ARGS", SERVER_ERR = "#SERVER_ERR", ACCESS_DENIED = "#ACCESS_DENIED", 
    SERVER_FULL = "#SERVER_FULL", GAME_STARTED = "#GAME_STARTED", NAME_TAKEN = "#NAME_TAKEN", 
    NOT_YOUR_TURN = "#NOT_YOUR_TURN", NOT_ENOUGH_PLAYERS = "#NOT_ENOUGH_PLAYERS", GAME_ENDED = "#GAME_ENDED";
}
